### ISSUE TITLE
The Vue Semantic Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.

### ISSUE THREAD

**Issue by zanderzhg** [dishait/tov-template#53]
### nodejs 版本

Node.js: 16.14.2

(推荐使用 `v16` 以上)

<br />

### 包管理器及其版本 

pnpm 8.2.0

(推荐使用 `pnpm`)

<br />

### 系统
vscode Version: 1.77.3
OS: Windows_NT x64 10.0.19044

(该项目开发环境系统为 `win11`)

<br />
<br />

### 描述

volar 报
`at G:\Scoop\persist\vscode\data\extensions\vue.volar-1.2.0-win32-x64\dist\node\server.js:846:9951
    at Array.map (<anonymous>)
    at ewe (G:\Scoop\persist\vscode\data\extensions\vue.volar-1.2.0-win32-x64\dist\node\server.js:846:9944)
    at Object.rwe (G:\Scoop\persist\vscode\data\extensions\vue.volar-1.2.0-win32-x64\dist\node\server.js:846:20241)
    at Object.kIe (G:\Scoop\persist\vscode\data\extensions\vue.volar-1.2.0-win32-x64\dist\node\server.js:7320:3900)
    at Object.resolveConfig (G:\Scoop\persist\vscode\data\extensions\vue.volar-1.2.0-win32-x64\dist\node\server.js:7324:8994)
    at Object.d [as getLanguageService] (G:\Scoop\persist\vscode\data\extensions\vue.volar-1.2.0-win32-x64\dist\node\server.js:510:1933)
    at G:\Scoop\persist\vscode\data\extensions\vue.volar-1.2.0-win32-x64\dist\node\server.js:510:32874
    at Generator.next (<anonymous>)
    at a (G:\Scoop\persist\vscode\data\extensions\vue.volar-1.2.0-win32-x64\dist\node\server.js:510:24057)
[Error - 10:05:46] The Vue Semantic Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.`
错误，我使用vitess就不会出现这个错误。请问老师您是怎么配置的。

<br />

### 预期结果

TODO

<br />

### 最小测试仓库

TODO

**Comment by markthree** [comment]
@zanderzhg 靓仔你好，已修复，请重新 `clone` 最新版本试试
